if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED MLRVST_PROJECT_VERSION)
    message(FATAL_ERROR "MLRVST_PROJECT_VERSION is required")
endif()

string(TIMESTAMP MLRVST_BUILD_STAMP "%Y-%m-%d %H:%M:%S")
string(TIMESTAMP MLRVST_BUILD_STAMP_COMPACT "%Y%m%d-%H%M%S")

string(CONCAT MLRVST_BUILD_INFO_CONTENT
    "#pragma once\n"
    "#define MLRVST_BUILD_VERSION \"${MLRVST_PROJECT_VERSION}\"\n"
    "#define MLRVST_BUILD_STAMP \"${MLRVST_BUILD_STAMP}\"\n"
    "#define MLRVST_BUILD_STAMP_COMPACT \"${MLRVST_BUILD_STAMP_COMPACT}\"\n")

set(MLRVST_BUILD_INFO_TMP "${OUTPUT_FILE}.tmp")
file(WRITE "${MLRVST_BUILD_INFO_TMP}" "${MLRVST_BUILD_INFO_CONTENT}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${MLRVST_BUILD_INFO_TMP}" "${OUTPUT_FILE}")
file(REMOVE "${MLRVST_BUILD_INFO_TMP}")
